# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'frm_main_window.ui'
##
## Created by: Qt User Interface Compiler version 6.10.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QGraphicsView, QHeaderView, QLabel,
    QLineEdit, QMainWindow, QMenu, QMenuBar,
    QPushButton, QSizePolicy, QStatusBar, QTableView,
    QWidget)

class Ui_frm_main_window(object):
    def setupUi(self, frm_main_window):
        if not frm_main_window.objectName():
            frm_main_window.setObjectName(u"frm_main_window")
        frm_main_window.resize(1200, 800)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(frm_main_window.sizePolicy().hasHeightForWidth())
        frm_main_window.setSizePolicy(sizePolicy)
        font = QFont()
        font.setPointSize(11)
        frm_main_window.setFont(font)
        self.actionSettings = QAction(frm_main_window)
        self.actionSettings.setObjectName(u"actionSettings")
        self.actionExit = QAction(frm_main_window)
        self.actionExit.setObjectName(u"actionExit")
        self.actionSingle_Card_Import = QAction(frm_main_window)
        self.actionSingle_Card_Import.setObjectName(u"actionSingle_Card_Import")
        self.actionBulk_Upload = QAction(frm_main_window)
        self.actionBulk_Upload.setObjectName(u"actionBulk_Upload")
        self.actionManual = QAction(frm_main_window)
        self.actionManual.setObjectName(u"actionManual")
        self.actionVersionInfo = QAction(frm_main_window)
        self.actionVersionInfo.setObjectName(u"actionVersionInfo")
        self.actionBulk_Card_Import = QAction(frm_main_window)
        self.actionBulk_Card_Import.setObjectName(u"actionBulk_Card_Import")
        self.centralwidget = QWidget(frm_main_window)
        self.centralwidget.setObjectName(u"centralwidget")
        self.le_callsign = QLineEdit(self.centralwidget)
        self.le_callsign.setObjectName(u"le_callsign")
        self.le_callsign.setGeometry(QRect(30, 60, 130, 30))
        self.le_itu_zone = QLineEdit(self.centralwidget)
        self.le_itu_zone.setObjectName(u"le_itu_zone")
        self.le_itu_zone.setGeometry(QRect(350, 140, 130, 30))
        self.le_cq_zone = QLineEdit(self.centralwidget)
        self.le_cq_zone.setObjectName(u"le_cq_zone")
        self.le_cq_zone.setGeometry(QRect(520, 140, 130, 30))
        self.le_dxcc_number = QLineEdit(self.centralwidget)
        self.le_dxcc_number.setObjectName(u"le_dxcc_number")
        self.le_dxcc_number.setGeometry(QRect(190, 140, 130, 30))
        self.le_dxcc = QLineEdit(self.centralwidget)
        self.le_dxcc.setObjectName(u"le_dxcc")
        self.le_dxcc.setGeometry(QRect(30, 140, 130, 30))
        self.le_mode = QLineEdit(self.centralwidget)
        self.le_mode.setObjectName(u"le_mode")
        self.le_mode.setGeometry(QRect(520, 60, 130, 30))
        self.le_band = QLineEdit(self.centralwidget)
        self.le_band.setObjectName(u"le_band")
        self.le_band.setGeometry(QRect(350, 60, 130, 30))
        self.le_year = QLineEdit(self.centralwidget)
        self.le_year.setObjectName(u"le_year")
        self.le_year.setGeometry(QRect(190, 60, 130, 30))
        self.lb_callsign = QLabel(self.centralwidget)
        self.lb_callsign.setObjectName(u"lb_callsign")
        self.lb_callsign.setGeometry(QRect(30, 30, 127, 27))
        self.lb_callsign.setFont(font)
        self.lb_callsign.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lb_band = QLabel(self.centralwidget)
        self.lb_band.setObjectName(u"lb_band")
        self.lb_band.setGeometry(QRect(350, 30, 127, 27))
        self.lb_band.setFont(font)
        self.lb_band.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lb_year = QLabel(self.centralwidget)
        self.lb_year.setObjectName(u"lb_year")
        self.lb_year.setGeometry(QRect(190, 30, 127, 27))
        self.lb_year.setFont(font)
        self.lb_year.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lb_dxcc = QLabel(self.centralwidget)
        self.lb_dxcc.setObjectName(u"lb_dxcc")
        self.lb_dxcc.setGeometry(QRect(30, 110, 127, 27))
        self.lb_dxcc.setFont(font)
        self.lb_dxcc.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lb_mode = QLabel(self.centralwidget)
        self.lb_mode.setObjectName(u"lb_mode")
        self.lb_mode.setGeometry(QRect(520, 30, 127, 27))
        self.lb_mode.setFont(font)
        self.lb_mode.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lb_itu_zone = QLabel(self.centralwidget)
        self.lb_itu_zone.setObjectName(u"lb_itu_zone")
        self.lb_itu_zone.setGeometry(QRect(350, 110, 127, 27))
        self.lb_itu_zone.setFont(font)
        self.lb_itu_zone.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lb_dxcc_number = QLabel(self.centralwidget)
        self.lb_dxcc_number.setObjectName(u"lb_dxcc_number")
        self.lb_dxcc_number.setGeometry(QRect(190, 110, 127, 27))
        self.lb_dxcc_number.setFont(font)
        self.lb_dxcc_number.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lb_cq_zone = QLabel(self.centralwidget)
        self.lb_cq_zone.setObjectName(u"lb_cq_zone")
        self.lb_cq_zone.setGeometry(QRect(520, 110, 127, 27))
        self.lb_cq_zone.setFont(font)
        self.lb_cq_zone.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.btn_search_qsl = QPushButton(self.centralwidget)
        self.btn_search_qsl.setObjectName(u"btn_search_qsl")
        self.btn_search_qsl.setGeometry(QRect(710, 60, 85, 27))
        font1 = QFont()
        font1.setPointSize(11)
        font1.setBold(True)
        self.btn_search_qsl.setFont(font1)
        self.btn_reset = QPushButton(self.centralwidget)
        self.btn_reset.setObjectName(u"btn_reset")
        self.btn_reset.setGeometry(QRect(710, 140, 85, 27))
        self.btn_reset.setFont(font1)
        self.grv_logo = QGraphicsView(self.centralwidget)
        self.grv_logo.setObjectName(u"grv_logo")
        self.grv_logo.setGeometry(QRect(865, 20, 291, 151))
        self.tbl_search_view = QTableView(self.centralwidget)
        self.tbl_search_view.setObjectName(u"tbl_search_view")
        self.tbl_search_view.setGeometry(QRect(30, 210, 1131, 451))
        self.btn_show = QPushButton(self.centralwidget)
        self.btn_show.setObjectName(u"btn_show")
        self.btn_show.setGeometry(QRect(600, 690, 85, 27))
        self.btn_show.setFont(font1)
        self.btn_download = QPushButton(self.centralwidget)
        self.btn_download.setObjectName(u"btn_download")
        self.btn_download.setGeometry(QRect(470, 690, 85, 27))
        self.btn_download.setFont(font1)
        self.btn_unmark_all = QPushButton(self.centralwidget)
        self.btn_unmark_all.setObjectName(u"btn_unmark_all")
        self.btn_unmark_all.setGeometry(QRect(200, 690, 85, 27))
        self.btn_unmark_all.setFont(font1)
        self.btn_mark_all = QPushButton(self.centralwidget)
        self.btn_mark_all.setObjectName(u"btn_mark_all")
        self.btn_mark_all.setGeometry(QRect(70, 690, 85, 27))
        self.btn_mark_all.setFont(font1)
        self.btn_exit_program = QPushButton(self.centralwidget)
        self.btn_exit_program.setObjectName(u"btn_exit_program")
        self.btn_exit_program.setGeometry(QRect(1040, 690, 85, 27))
        self.btn_exit_program.setFont(font1)
        frm_main_window.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(frm_main_window)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1200, 33))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuUpload = QMenu(self.menubar)
        self.menuUpload.setObjectName(u"menuUpload")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        frm_main_window.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(frm_main_window)
        self.statusbar.setObjectName(u"statusbar")
        frm_main_window.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuUpload.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionSettings)
        self.menuFile.addAction(self.actionExit)
        self.menuUpload.addAction(self.actionSingle_Card_Import)
        self.menuUpload.addAction(self.actionBulk_Card_Import)
        self.menuHelp.addAction(self.actionManual)
        self.menuHelp.addAction(self.actionVersionInfo)

        self.retranslateUi(frm_main_window)

        QMetaObject.connectSlotsByName(frm_main_window)
    # setupUi

    def retranslateUi(self, frm_main_window):
        frm_main_window.setWindowTitle(QCoreApplication.translate("frm_main_window", u"MainWindow", None))
        self.actionSettings.setText(QCoreApplication.translate("frm_main_window", u"Settings", None))
        self.actionExit.setText(QCoreApplication.translate("frm_main_window", u"Exit", None))
        self.actionSingle_Card_Import.setText(QCoreApplication.translate("frm_main_window", u"Single Card Import", None))
        self.actionBulk_Upload.setText(QCoreApplication.translate("frm_main_window", u"Bulk Upload", None))
        self.actionManual.setText(QCoreApplication.translate("frm_main_window", u"Manual", None))
        self.actionVersionInfo.setText(QCoreApplication.translate("frm_main_window", u"About", None))
        self.actionBulk_Card_Import.setText(QCoreApplication.translate("frm_main_window", u"Bulk Card Import", None))
        self.lb_callsign.setText(QCoreApplication.translate("frm_main_window", u"Callsign", None))
        self.lb_band.setText(QCoreApplication.translate("frm_main_window", u"Band", None))
        self.lb_year.setText(QCoreApplication.translate("frm_main_window", u"Year", None))
        self.lb_dxcc.setText(QCoreApplication.translate("frm_main_window", u"DXCC", None))
        self.lb_mode.setText(QCoreApplication.translate("frm_main_window", u"Mode", None))
        self.lb_itu_zone.setText(QCoreApplication.translate("frm_main_window", u"ITU Zone", None))
        self.lb_dxcc_number.setText(QCoreApplication.translate("frm_main_window", u"DXCC Number", None))
        self.lb_cq_zone.setText(QCoreApplication.translate("frm_main_window", u"CQ Zone", None))
        self.btn_search_qsl.setText(QCoreApplication.translate("frm_main_window", u"Search", None))
        self.btn_reset.setText(QCoreApplication.translate("frm_main_window", u"Reset", None))
        self.btn_show.setText(QCoreApplication.translate("frm_main_window", u"Show", None))
        self.btn_download.setText(QCoreApplication.translate("frm_main_window", u"Download", None))
        self.btn_unmark_all.setText(QCoreApplication.translate("frm_main_window", u"Unmark all", None))
        self.btn_mark_all.setText(QCoreApplication.translate("frm_main_window", u"Mark all", None))
        self.btn_exit_program.setText(QCoreApplication.translate("frm_main_window", u"EXIT", None))
        self.menuFile.setTitle(QCoreApplication.translate("frm_main_window", u"File", None))
        self.menuUpload.setTitle(QCoreApplication.translate("frm_main_window", u"Import", None))
        self.menuHelp.setTitle(QCoreApplication.translate("frm_main_window", u"Help", None))
    # retranslateUi

