# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'frm_main_window.ui'
##
## Created by: Qt User Interface Compiler version 6.10.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QHeaderView, QLabel, QLineEdit,
    QMainWindow, QMenu, QMenuBar, QPushButton,
    QSizePolicy, QStatusBar, QTableView, QWidget)

class Ui_frm_main_window(object):
    def setupUi(self, frm_main_window):
        if not frm_main_window.objectName():
            frm_main_window.setObjectName(u"frm_main_window")
        frm_main_window.resize(960, 700)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(frm_main_window.sizePolicy().hasHeightForWidth())
        frm_main_window.setSizePolicy(sizePolicy)
        font = QFont()
        font.setPointSize(11)
        frm_main_window.setFont(font)
        self.actionSettings = QAction(frm_main_window)
        self.actionSettings.setObjectName(u"actionSettings")
        self.actionExit = QAction(frm_main_window)
        self.actionExit.setObjectName(u"actionExit")
        self.actionSingle_Card_Import = QAction(frm_main_window)
        self.actionSingle_Card_Import.setObjectName(u"actionSingle_Card_Import")
        self.actionBulk_Upload = QAction(frm_main_window)
        self.actionBulk_Upload.setObjectName(u"actionBulk_Upload")
        self.actionManual = QAction(frm_main_window)
        self.actionManual.setObjectName(u"actionManual")
        self.actionVersionInfo = QAction(frm_main_window)
        self.actionVersionInfo.setObjectName(u"actionVersionInfo")
        self.actionBulk_Card_Import = QAction(frm_main_window)
        self.actionBulk_Card_Import.setObjectName(u"actionBulk_Card_Import")
        self.centralwidget = QWidget(frm_main_window)
        self.centralwidget.setObjectName(u"centralwidget")
        self.txt_search_field_main = QLineEdit(self.centralwidget)
        self.txt_search_field_main.setObjectName(u"txt_search_field_main")
        self.txt_search_field_main.setGeometry(QRect(520, 50, 421, 30))
        self.lb_searchfield_main = QLabel(self.centralwidget)
        self.lb_searchfield_main.setObjectName(u"lb_searchfield_main")
        self.lb_searchfield_main.setGeometry(QRect(520, 20, 421, 27))
        self.lb_searchfield_main.setFont(font)
        self.lb_searchfield_main.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.btn_search_main = QPushButton(self.centralwidget)
        self.btn_search_main.setObjectName(u"btn_search_main")
        self.btn_search_main.setGeometry(QRect(850, 110, 85, 27))
        font1 = QFont()
        font1.setPointSize(11)
        font1.setBold(True)
        self.btn_search_main.setFont(font1)
        self.btn_reset_main = QPushButton(self.centralwidget)
        self.btn_reset_main.setObjectName(u"btn_reset_main")
        self.btn_reset_main.setGeometry(QRect(850, 160, 85, 27))
        self.btn_reset_main.setFont(font1)
        self.tbl_data_view_main = QTableView(self.centralwidget)
        self.tbl_data_view_main.setObjectName(u"tbl_data_view_main")
        self.tbl_data_view_main.setGeometry(QRect(10, 200, 941, 441))
        self.btn_show = QPushButton(self.centralwidget)
        self.btn_show.setObjectName(u"btn_show")
        self.btn_show.setGeometry(QRect(600, 690, 85, 27))
        self.btn_show.setFont(font1)
        self.btn_download = QPushButton(self.centralwidget)
        self.btn_download.setObjectName(u"btn_download")
        self.btn_download.setGeometry(QRect(470, 690, 85, 27))
        self.btn_download.setFont(font1)
        self.btn_unmark_all = QPushButton(self.centralwidget)
        self.btn_unmark_all.setObjectName(u"btn_unmark_all")
        self.btn_unmark_all.setGeometry(QRect(200, 690, 85, 27))
        self.btn_unmark_all.setFont(font1)
        self.btn_mark_all = QPushButton(self.centralwidget)
        self.btn_mark_all.setObjectName(u"btn_mark_all")
        self.btn_mark_all.setGeometry(QRect(70, 690, 85, 27))
        self.btn_mark_all.setFont(font1)
        self.btn_exit_program = QPushButton(self.centralwidget)
        self.btn_exit_program.setObjectName(u"btn_exit_program")
        self.btn_exit_program.setGeometry(QRect(1040, 690, 85, 27))
        self.btn_exit_program.setFont(font1)
        self.btn_markall_main = QPushButton(self.centralwidget)
        self.btn_markall_main.setObjectName(u"btn_markall_main")
        self.btn_markall_main.setGeometry(QRect(520, 110, 85, 27))
        self.btn_markall_main.setFont(font1)
        self.btn_unmarkall_main = QPushButton(self.centralwidget)
        self.btn_unmarkall_main.setObjectName(u"btn_unmarkall_main")
        self.btn_unmarkall_main.setGeometry(QRect(520, 160, 85, 27))
        self.btn_unmarkall_main.setFont(font1)
        self.btn_export_image = QPushButton(self.centralwidget)
        self.btn_export_image.setObjectName(u"btn_export_image")
        self.btn_export_image.setGeometry(QRect(690, 160, 85, 27))
        self.btn_export_image.setFont(font1)
        self.btn_show_image = QPushButton(self.centralwidget)
        self.btn_show_image.setObjectName(u"btn_show_image")
        self.btn_show_image.setGeometry(QRect(690, 110, 85, 27))
        self.btn_show_image.setFont(font1)
        self.lb_preview_image_main = QLabel(self.centralwidget)
        self.lb_preview_image_main.setObjectName(u"lb_preview_image_main")
        self.lb_preview_image_main.setGeometry(QRect(140, 20, 255, 170))
        frm_main_window.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(frm_main_window)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 960, 33))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuUpload = QMenu(self.menubar)
        self.menuUpload.setObjectName(u"menuUpload")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        frm_main_window.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(frm_main_window)
        self.statusbar.setObjectName(u"statusbar")
        frm_main_window.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuUpload.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionSettings)
        self.menuFile.addAction(self.actionExit)
        self.menuUpload.addAction(self.actionSingle_Card_Import)
        self.menuUpload.addAction(self.actionBulk_Card_Import)
        self.menuHelp.addAction(self.actionManual)
        self.menuHelp.addAction(self.actionVersionInfo)

        self.retranslateUi(frm_main_window)

        QMetaObject.connectSlotsByName(frm_main_window)
    # setupUi

    def retranslateUi(self, frm_main_window):
        frm_main_window.setWindowTitle(QCoreApplication.translate("frm_main_window", u"MainWindow", None))
        self.actionSettings.setText(QCoreApplication.translate("frm_main_window", u"Settings", None))
        self.actionExit.setText(QCoreApplication.translate("frm_main_window", u"Exit", None))
        self.actionSingle_Card_Import.setText(QCoreApplication.translate("frm_main_window", u"Single Card Import", None))
        self.actionBulk_Upload.setText(QCoreApplication.translate("frm_main_window", u"Bulk Upload", None))
        self.actionManual.setText(QCoreApplication.translate("frm_main_window", u"Manual", None))
        self.actionVersionInfo.setText(QCoreApplication.translate("frm_main_window", u"About", None))
        self.actionBulk_Card_Import.setText(QCoreApplication.translate("frm_main_window", u"Bulk Card Import", None))
        self.lb_searchfield_main.setText(QCoreApplication.translate("frm_main_window", u"Search for . . . ", None))
        self.btn_search_main.setText(QCoreApplication.translate("frm_main_window", u"Search", None))
        self.btn_reset_main.setText(QCoreApplication.translate("frm_main_window", u"Reset", None))
        self.btn_show.setText(QCoreApplication.translate("frm_main_window", u"Show", None))
        self.btn_download.setText(QCoreApplication.translate("frm_main_window", u"Download", None))
        self.btn_unmark_all.setText(QCoreApplication.translate("frm_main_window", u"Unmark all", None))
        self.btn_mark_all.setText(QCoreApplication.translate("frm_main_window", u"Mark all", None))
        self.btn_exit_program.setText(QCoreApplication.translate("frm_main_window", u"EXIT", None))
        self.btn_markall_main.setText(QCoreApplication.translate("frm_main_window", u"Mark all", None))
        self.btn_unmarkall_main.setText(QCoreApplication.translate("frm_main_window", u"Unmark all", None))
        self.btn_export_image.setText(QCoreApplication.translate("frm_main_window", u"Export", None))
        self.btn_show_image.setText(QCoreApplication.translate("frm_main_window", u"Show", None))
        self.lb_preview_image_main.setText("")
        self.menuFile.setTitle(QCoreApplication.translate("frm_main_window", u"File", None))
        self.menuUpload.setTitle(QCoreApplication.translate("frm_main_window", u"Import", None))
        self.menuHelp.setTitle(QCoreApplication.translate("frm_main_window", u"Help", None))
    # retranslateUi

