# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'frm_upload.ui'
##
## Created by: Qt User Interface Compiler version 6.10.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QDialog, QLabel, QLineEdit,
    QPushButton, QSizePolicy, QWidget)

class Ui_frm_upload(object):
    def setupUi(self, frm_upload):
        if not frm_upload.objectName():
            frm_upload.setObjectName(u"frm_upload")
        frm_upload.setEnabled(True)
        frm_upload.resize(800, 600)
        self.btn_upload_bulkcard = QPushButton(frm_upload)
        self.btn_upload_bulkcard.setObjectName(u"btn_upload_bulkcard")
        self.btn_upload_bulkcard.setGeometry(QRect(650, 450, 85, 27))
        font = QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.btn_upload_bulkcard.setFont(font)
        self.btn_reset_bulkcard = QPushButton(frm_upload)
        self.btn_reset_bulkcard.setObjectName(u"btn_reset_bulkcard")
        self.btn_reset_bulkcard.setGeometry(QRect(530, 450, 85, 27))
        self.btn_reset_bulkcard.setFont(font)
        self.lb_warning_bulk_upload_1 = QLabel(frm_upload)
        self.lb_warning_bulk_upload_1.setObjectName(u"lb_warning_bulk_upload_1")
        self.lb_warning_bulk_upload_1.setGeometry(QRect(78, 365, 671, 51))
        self.btn_cancel_frm_upload = QPushButton(frm_upload)
        self.btn_cancel_frm_upload.setObjectName(u"btn_cancel_frm_upload")
        self.btn_cancel_frm_upload.setGeometry(QRect(670, 520, 85, 27))
        self.btn_cancel_frm_upload.setFont(font)
        self.lb_time_1 = QLabel(frm_upload)
        self.lb_time_1.setObjectName(u"lb_time_1")
        self.lb_time_1.setGeometry(QRect(300, 100, 111, 27))
        font1 = QFont()
        font1.setPointSize(11)
        self.lb_time_1.setFont(font1)
        self.lb_time_1.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lb_path_bulkcard = QLabel(frm_upload)
        self.lb_path_bulkcard.setObjectName(u"lb_path_bulkcard")
        self.lb_path_bulkcard.setGeometry(QRect(60, 420, 301, 27))
        self.lb_path_bulkcard.setFont(font1)
        self.lb_path_bulkcard.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.le_date_1 = QLineEdit(frm_upload)
        self.le_date_1.setObjectName(u"le_date_1")
        self.le_date_1.setGeometry(QRect(190, 130, 111, 30))
        self.btn_reset_singlecard = QPushButton(frm_upload)
        self.btn_reset_singlecard.setObjectName(u"btn_reset_singlecard")
        self.btn_reset_singlecard.setGeometry(QRect(540, 250, 85, 27))
        self.btn_reset_singlecard.setFont(font)
        self.lb_mode_1 = QLabel(frm_upload)
        self.lb_mode_1.setObjectName(u"lb_mode_1")
        self.lb_mode_1.setGeometry(QRect(520, 100, 101, 27))
        self.lb_mode_1.setFont(font1)
        self.lb_mode_1.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.le_callsign_5 = QLineEdit(frm_upload)
        self.le_callsign_5.setObjectName(u"le_callsign_5")
        self.le_callsign_5.setGeometry(QRect(520, 130, 101, 30))
        self.le_path_bulkcard = QLineEdit(frm_upload)
        self.le_path_bulkcard.setObjectName(u"le_path_bulkcard")
        self.le_path_bulkcard.setGeometry(QRect(60, 450, 300, 30))
        self.le_path_bulkcard.setFont(font1)
        self.le_dxcc_number_1 = QLineEdit(frm_upload)
        self.le_dxcc_number_1.setObjectName(u"le_dxcc_number_1")
        self.le_dxcc_number_1.setGeometry(QRect(630, 130, 111, 30))
        self.lb_band_1 = QLabel(frm_upload)
        self.lb_band_1.setObjectName(u"lb_band_1")
        self.lb_band_1.setGeometry(QRect(410, 100, 101, 27))
        self.lb_band_1.setFont(font1)
        self.lb_band_1.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.le_time_1 = QLineEdit(frm_upload)
        self.le_time_1.setObjectName(u"le_time_1")
        self.le_time_1.setGeometry(QRect(310, 130, 91, 30))
        self.btn_search_path_singlecard_upload = QPushButton(frm_upload)
        self.btn_search_path_singlecard_upload.setObjectName(u"btn_search_path_singlecard_upload")
        self.btn_search_path_singlecard_upload.setGeometry(QRect(390, 210, 85, 27))
        self.btn_search_path_singlecard_upload.setFont(font)
        self.btn_upload_singlecard = QPushButton(frm_upload)
        self.btn_upload_singlecard.setObjectName(u"btn_upload_singlecard")
        self.btn_upload_singlecard.setGeometry(QRect(660, 250, 85, 27))
        self.btn_upload_singlecard.setFont(font)
        self.lb_bulk_card_upload_section = QLabel(frm_upload)
        self.lb_bulk_card_upload_section.setObjectName(u"lb_bulk_card_upload_section")
        self.lb_bulk_card_upload_section.setGeometry(QRect(100, 310, 601, 27))
        self.lb_bulk_card_upload_section.setFont(font1)
        self.lb_bulk_card_upload_section.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lb_date_1 = QLabel(frm_upload)
        self.lb_date_1.setObjectName(u"lb_date_1")
        self.lb_date_1.setGeometry(QRect(180, 100, 127, 27))
        self.lb_date_1.setFont(font1)
        self.lb_date_1.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.le_callsign_1 = QLineEdit(frm_upload)
        self.le_callsign_1.setObjectName(u"le_callsign_1")
        self.le_callsign_1.setGeometry(QRect(70, 130, 111, 30))
        self.lb_path_singlecard = QLabel(frm_upload)
        self.lb_path_singlecard.setObjectName(u"lb_path_singlecard")
        self.lb_path_singlecard.setGeometry(QRect(60, 180, 301, 27))
        self.lb_path_singlecard.setFont(font1)
        self.lb_path_singlecard.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.le_path_singlecard = QLineEdit(frm_upload)
        self.le_path_singlecard.setObjectName(u"le_path_singlecard")
        self.le_path_singlecard.setGeometry(QRect(70, 210, 300, 30))
        self.le_path_singlecard.setFont(font1)
        self.lb_dxcc_number_1 = QLabel(frm_upload)
        self.lb_dxcc_number_1.setObjectName(u"lb_dxcc_number_1")
        self.lb_dxcc_number_1.setGeometry(QRect(630, 100, 111, 27))
        self.lb_dxcc_number_1.setFont(font1)
        self.lb_dxcc_number_1.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lb_single_card_upload_section = QLabel(frm_upload)
        self.lb_single_card_upload_section.setObjectName(u"lb_single_card_upload_section")
        self.lb_single_card_upload_section.setGeometry(QRect(110, 50, 601, 27))
        self.lb_single_card_upload_section.setFont(font1)
        self.lb_single_card_upload_section.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lb_callsign_1 = QLabel(frm_upload)
        self.lb_callsign_1.setObjectName(u"lb_callsign_1")
        self.lb_callsign_1.setGeometry(QRect(70, 100, 127, 27))
        self.lb_callsign_1.setFont(font1)
        self.lb_callsign_1.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.btn_search_path_bulkcard_upload = QPushButton(frm_upload)
        self.btn_search_path_bulkcard_upload.setObjectName(u"btn_search_path_bulkcard_upload")
        self.btn_search_path_bulkcard_upload.setGeometry(QRect(380, 450, 85, 27))
        self.btn_search_path_bulkcard_upload.setFont(font)
        self.le_mode_1 = QLineEdit(frm_upload)
        self.le_mode_1.setObjectName(u"le_mode_1")
        self.le_mode_1.setGeometry(QRect(410, 130, 101, 30))

        self.retranslateUi(frm_upload)

        QMetaObject.connectSlotsByName(frm_upload)
    # setupUi

    def retranslateUi(self, frm_upload):
        frm_upload.setWindowTitle(QCoreApplication.translate("frm_upload", u"Dialog", None))
        self.btn_upload_bulkcard.setText(QCoreApplication.translate("frm_upload", u"Upload", None))
        self.btn_reset_bulkcard.setText(QCoreApplication.translate("frm_upload", u"Reset", None))
        self.lb_warning_bulk_upload_1.setText(QCoreApplication.translate("frm_upload", u"Warning for correct folder structure and filename syntax!!!", None))
        self.btn_cancel_frm_upload.setText(QCoreApplication.translate("frm_upload", u"Cancel", None))
        self.lb_time_1.setText(QCoreApplication.translate("frm_upload", u"Time", None))
        self.lb_path_bulkcard.setText(QCoreApplication.translate("frm_upload", u"Path for Bulk Card Upload", None))
        self.btn_reset_singlecard.setText(QCoreApplication.translate("frm_upload", u"Reset", None))
        self.lb_mode_1.setText(QCoreApplication.translate("frm_upload", u"Mode", None))
        self.lb_band_1.setText(QCoreApplication.translate("frm_upload", u"Band", None))
        self.btn_search_path_singlecard_upload.setText(QCoreApplication.translate("frm_upload", u"Search", None))
        self.btn_upload_singlecard.setText(QCoreApplication.translate("frm_upload", u"Upload", None))
        self.lb_bulk_card_upload_section.setText(QCoreApplication.translate("frm_upload", u"Bulk Card Upload Section for Eqsl downloaded by Log4OM", None))
        self.lb_date_1.setText(QCoreApplication.translate("frm_upload", u"Date", None))
        self.lb_path_singlecard.setText(QCoreApplication.translate("frm_upload", u"Path for Single Card Upload", None))
        self.lb_dxcc_number_1.setText(QCoreApplication.translate("frm_upload", u"DXCC Number", None))
        self.lb_single_card_upload_section.setText(QCoreApplication.translate("frm_upload", u"Single Card Upload Section", None))
        self.lb_callsign_1.setText(QCoreApplication.translate("frm_upload", u"Callsign", None))
        self.btn_search_path_bulkcard_upload.setText(QCoreApplication.translate("frm_upload", u"Search", None))
    # retranslateUi

